<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS002_login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>muhammadtajussyaroff@gmail.com;</mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>db236f20-8f17-4675-aeb6-749b5d81d019</testSuiteGuid>
   <testCaseLink>
      <guid>82c2b410-dbd6-4d83-8a11-f58ea576441f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/scenario/login_succes</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69edfaa4-41d0-49f8-8097-fabd0a623f31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9280772b-261f-4451-930d-da7cac15fdbb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a6cbc88-9943-4a1f-bde5-d456d629be76</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4e4bea1-06e1-4bfc-a1e1-5eff8c73b7cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/scenario/Login_failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a413728-5278-40c7-960c-17a01ba31af4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48fc3608-4f2e-4de4-88d4-f43c378bf304</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
