<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Android</name>
   <tag></tag>
   <elementGuidId>b6ba1657-201e-46f6-8e4d-1febe39ec966</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.cat-item.cat-item-24 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='woocommerce_product_categories-2']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Android&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d4d65472-c9c9-4555-9029-5969f98d8bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/product-category/android/</value>
      <webElementGuid>759ccaf6-b6ca-4b29-af7c-2527e7d6b765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Android</value>
      <webElementGuid>c8e0b254-ef56-420e-ae8c-3807fe2c5e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;woocommerce_product_categories-2&quot;)/ul[@class=&quot;product-categories&quot;]/li[@class=&quot;cat-item cat-item-24&quot;]/a[1]</value>
      <webElementGuid>c16e0c8c-4eca-4269-9908-51d721f08f0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='woocommerce_product_categories-2']/ul/li/a</value>
      <webElementGuid>42984501-646c-4f3e-ae7b-60636a945d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Android')]</value>
      <webElementGuid>6b4ca948-93b8-4394-af49-73c57a3d9f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Categories'])[1]/following::a[1]</value>
      <webElementGuid>13d91f22-ceb7-48a2-a27d-ba4529c511d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹500'])[1]/following::a[1]</value>
      <webElementGuid>2c65a86e-033e-4034-952d-17d3ecf864e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1)'])[1]/preceding::a[1]</value>
      <webElementGuid>57f1aefd-9ad2-48bc-a2b9-1429165f9a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HTML'])[1]/preceding::a[1]</value>
      <webElementGuid>09230462-5c8b-4c1a-9d48-6c42307cf265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Android']/parent::*</value>
      <webElementGuid>d6ffe8ba-11eb-4e92-98f4-2fac82e53b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://practice.automationtesting.in/product-category/android/')]</value>
      <webElementGuid>eccd8f1c-0987-417b-8a75-7e9d825b1f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li/a</value>
      <webElementGuid>2b88e5c6-f48f-4bb3-bcc6-5746089fc7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://practice.automationtesting.in/product-category/android/' and (text() = 'Android' or . = 'Android')]</value>
      <webElementGuid>e2b0903a-d5f2-42b7-a547-e9f6405957c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
