<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_selenium</name>
   <tag></tag>
   <elementGuidId>2454f6ad-1c18-4de4-a39a-08e4231e5dd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.cat-item.cat-item-17 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='woocommerce_product_categories-2']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;selenium&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>190b8fd0-a54d-49eb-97a8-0b76da9b3094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://practice.automationtesting.in/product-category/selenium/</value>
      <webElementGuid>bb1a5ff5-793e-4c5a-9d7f-6624e95e2173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>selenium</value>
      <webElementGuid>fd25da0e-2fd3-448b-b6e5-cc624d05fdfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;woocommerce_product_categories-2&quot;)/ul[@class=&quot;product-categories&quot;]/li[@class=&quot;cat-item cat-item-17&quot;]/a[1]</value>
      <webElementGuid>796bb02a-a856-47b7-aea9-a37e35fc7d85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='woocommerce_product_categories-2']/ul/li[4]/a</value>
      <webElementGuid>6eb9f133-0139-464a-92b0-3ff709dec176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'selenium')]</value>
      <webElementGuid>bdcc2f2c-1eb2-49cd-80df-beb1a4d4d54d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(3)'])[2]/following::a[1]</value>
      <webElementGuid>d685b2c3-a27d-48ee-955b-b197e6399f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript'])[1]/following::a[1]</value>
      <webElementGuid>7d87f2dd-8f83-4e31-b719-cec95493764d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1)'])[2]/preceding::a[1]</value>
      <webElementGuid>17c36957-323f-4775-a0b5-a0e6aae95caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe Here'])[1]/preceding::a[7]</value>
      <webElementGuid>222c752f-6bb9-4ad8-83e8-b8a0d10adeae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='selenium']/parent::*</value>
      <webElementGuid>d98a6349-3c1e-407e-8fcc-698ccd8eb5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://practice.automationtesting.in/product-category/selenium/')]</value>
      <webElementGuid>c018a0be-598e-42a7-8d34-64d08e3c17d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[4]/a</value>
      <webElementGuid>205cb9bd-da77-4115-8a49-af36ee682436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://practice.automationtesting.in/product-category/selenium/' and (text() = 'selenium' or . = 'selenium')]</value>
      <webElementGuid>669e589c-9826-45a2-9815-5473090d7da4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
